apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: kubernetes-work
spec:
  ingressClassName: traefik
  rules:
    - host: kubernetes-work.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
