apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: kubernetes-work
spec:
  type: ClusterIP
  selector:
    app: kubernetes-work-web
  ports:
    - name: http
      port: 80
      targetPort: http
